version: '3.4'

networks:
  kafka-net:
    driver: bridge

services:
  im-varsel-database:
    build:
      context: ./postgres
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  im_varsel_zookeeper:
    image: 'bitnami/zookeeper:3.6'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  im_varsel_kafka:
    image: 'bitnami/kafka:2.8.0'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=im_varsel_zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - im_varsel_zookeeper
volumes:
  data:
