apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: im-varsel
  namespace: default
  labels:
    team: helsearbeidsgiver
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 10
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  ingresses:
    - https://im-varsel.nais.preprod.local
    - https://im-varsel.dev-fss.nais.io
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/im-varsel/default
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvimvarsel
  webproxy: true
  env:
  - name: KOIN_PROFILE
    value: PREPROD
  - name: DATABASE_HOST
    value: b27dbvl013.preprod.local
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: im-varsel
  - name: VAULT_MOUNTPATH
    value: postgresql/preprod-fss/
  - name: KAFKA_ENDPOINTS
    value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
  - name: PARTNER_GATEWAY_ALTINN_ENDPOINT
    value: https://pep-gw-q1.oera-q.local:9443/ekstern/altinn/BehandleAltinnMelding/v1
  - name: SECURITYTOKENSERVICE_URL
    value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
  - name: SECURITYTOKENSERVICE_REST_URL
    value: https://security-token-service.nais.preprod.local/rest/v1/sts/token
  - name: INNTEKTSMELDING_VARSEL_TOPIC_NAME
    value: helse-spam-mottak-test
