apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: im-varsel
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver

spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
    periodSeconds: 3
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 10
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  ingresses:
    - https://im-varsel.nais.adeo.no
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/im-varsel/default
        mountPath: /var/run/secrets/nais.io/vault
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvimvarsel
  webproxy: true
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
  kafka:
    pool: nav-prod
  env:
    - name: KOIN_PROFILE
      value: PROD
    - name: DATABASE_HOST
      value: A01DBVL009.adeo.no
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: im-varsel
    - name: VAULT_MOUNTPATH
      value: postgresql/prod-fss/
    - name: PARTNER_GATEWAY_ALTINN_ENDPOINT
      value: https://pep-gw.oera.no:9443/ekstern/altinn/BehandleAltinnMelding/v1
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: SECURITYTOKENSERVICE_REST_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: INNTEKTSMELDING_VARSEL_AIVEN_TOPIC_NAME
      value: tbd.aapen-helse-spre-arbeidsgiver
    - name: KAFKA_ENDPOINTS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443
    - name: DOKARKIV_URL
      value: https://dokarkiv.nais.adeo.no
    - name: ALTINN_BREVUTSENDELSE_UI_ENABLED
      value: "false"
    - name: DATAPAKKE_ID
      value: "5683d0148392e99e79737fe6889aae68"
    - name: DATAPAKKE_API_URL
      value: "https://datakatalog-api.intern.nav.no/v1/datapackage"
    - name: ENHETSREGISTERET
      value: https://data.brreg.no/enhetsregisteret/api/underenheter/
